CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE theaters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    modified_by VARCHAR(255) NOT NULL,
    name VARCHAR(160) NOT NULL,
    owner_subject VARCHAR(255) NOT NULL,
    address VARCHAR(500) NOT NULL,
    city VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    time_zone VARCHAR(64) NOT NULL
);

CREATE TABLE auditoriums (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    modified_by VARCHAR(255) NOT NULL,
    theater_id BIGINT NOT NULL REFERENCES theaters(id),
    name VARCHAR(100) NOT NULL,
    CONSTRAINT uq_auditorium_name_per_theater UNIQUE (theater_id, name)
);

CREATE TABLE seat_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    modified_by VARCHAR(255) NOT NULL,
    auditorium_id BIGINT NOT NULL REFERENCES auditoriums(id),
    code VARCHAR(40) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    default_price NUMERIC(12, 2) NOT NULL CHECK (default_price > 0),
    CONSTRAINT uq_seat_type_per_auditorium UNIQUE (auditorium_id, code)
);

CREATE TABLE seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    modified_by VARCHAR(255) NOT NULL,
    auditorium_id BIGINT NOT NULL REFERENCES auditoriums(id),
    seat_type_id BIGINT NOT NULL REFERENCES seat_types(id),
    row_label VARCHAR(10) NOT NULL,
    seat_number INTEGER NOT NULL CHECK (seat_number > 0),
    CONSTRAINT uq_seat_location_per_auditorium UNIQUE (auditorium_id, row_label, seat_number)
);

CREATE TABLE scheduled_shows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    modified_by VARCHAR(255) NOT NULL,
    auditorium_id BIGINT NOT NULL REFERENCES auditoriums(id),
    content_id VARCHAR(100) NOT NULL,
    content_title VARCHAR(250) NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
    intermission_starts_at TIMESTAMP WITH TIME ZONE,
    intermission_ends_at TIMESTAMP WITH TIME ZONE,
    available_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_show_time_order CHECK (starts_at < ends_at AND ends_at <= available_at)
);

CREATE INDEX ix_scheduled_show_auditorium_window ON scheduled_shows (auditorium_id, starts_at, available_at);
ALTER TABLE scheduled_shows ADD CONSTRAINT ex_scheduled_show_auditorium_window
    EXCLUDE USING gist (auditorium_id WITH =, tstzrange(starts_at, available_at, '[)') WITH &&);

CREATE TABLE show_seat_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    modified_by VARCHAR(255) NOT NULL,
    show_id BIGINT NOT NULL REFERENCES scheduled_shows(id),
    seat_type_id BIGINT NOT NULL REFERENCES seat_types(id),
    price NUMERIC(12, 2) NOT NULL CHECK (price > 0),
    CONSTRAINT uq_show_seat_type_price UNIQUE (show_id, seat_type_id)
);
