CREATE TABLE bookings (
    id UUID PRIMARY KEY,
    owner_subject VARCHAR(255) NOT NULL,
    show_id BIGINT NOT NULL,
    content_id VARCHAR(100) NOT NULL,
    content_title VARCHAR(250) NOT NULL,
    theater_name VARCHAR(160) NOT NULL,
    auditorium_name VARCHAR(100) NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL CHECK (total_amount > 0),
    currency VARCHAR(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    status VARCHAR(30) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    idempotency_key VARCHAR(128) NOT NULL,
    request_fingerprint VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_booking_owner_idempotency UNIQUE (owner_subject, idempotency_key)
);

CREATE INDEX ix_bookings_owner_created ON bookings (owner_subject, created_at DESC);
CREATE INDEX ix_bookings_expiry ON bookings (expires_at)
    WHERE status IN ('PENDING_PAYMENT', 'PAYMENT_PROCESSING');
CREATE INDEX ix_bookings_show ON bookings (show_id);

CREATE TABLE booking_seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id UUID NOT NULL REFERENCES bookings(id),
    show_id BIGINT NOT NULL,
    seat_id BIGINT NOT NULL,
    row_label VARCHAR(10) NOT NULL,
    seat_number INTEGER NOT NULL CHECK (seat_number > 0),
    seat_type VARCHAR(100) NOT NULL,
    price NUMERIC(12, 2) NOT NULL CHECK (price > 0),
    reservation_status VARCHAR(20) NOT NULL
);

CREATE INDEX ix_booking_seats_booking ON booking_seats (booking_id);
CREATE INDEX ix_booking_seats_show ON booking_seats (show_id);
-- Redis coordinates fast concurrent holds. This constraint remains the final
-- authority if Redis restarts, partitions, or two writers race a lease.
CREATE UNIQUE INDEX uq_active_show_seat ON booking_seats (show_id, seat_id)
    WHERE reservation_status IN ('HELD', 'CONFIRMED');

CREATE TABLE booking_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id UUID NOT NULL REFERENCES bookings(id),
    previous_status VARCHAR(30),
    current_status VARCHAR(30) NOT NULL,
    actor VARCHAR(255) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX ix_booking_audits_booking_created ON booking_audits (booking_id, created_at);

CREATE TABLE processed_payment_events (
    event_id UUID PRIMARY KEY,
    payload_hash VARCHAR(64) NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL
);
