CREATE TABLE payments (
    id UUID PRIMARY KEY,
    booking_id UUID NOT NULL,
    owner_subject VARCHAR(255) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    refunded_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (refunded_amount >= 0 AND refunded_amount <= amount),
    currency VARCHAR(3) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    provider_reference VARCHAR(160) NOT NULL UNIQUE,
    checkout_url VARCHAR(2048),
    failure_code VARCHAR(80),
    failure_message VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_payment_owner_idempotency UNIQUE (owner_subject, idempotency_key),
    CONSTRAINT ck_payment_currency_uppercase CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE INDEX ix_payments_owner_created ON payments (owner_subject, created_at DESC);
CREATE INDEX ix_payments_booking_status ON payments (booking_id, status);
CREATE UNIQUE INDEX uq_active_payment_per_booking ON payments (booking_id)
    WHERE status IN ('PENDING', 'SUCCEEDED', 'PARTIALLY_REFUNDED', 'REFUNDED');

CREATE TABLE payment_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id UUID NOT NULL REFERENCES payments(id),
    previous_status VARCHAR(30),
    current_status VARCHAR(30) NOT NULL,
    actor VARCHAR(255) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX ix_payment_audits_payment_created ON payment_audits (payment_id, created_at);

CREATE TABLE refunds (
    id UUID PRIMARY KEY,
    payment_id UUID NOT NULL REFERENCES payments(id),
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    status VARCHAR(30) NOT NULL,
    provider_reference VARCHAR(160) NOT NULL UNIQUE,
    reason VARCHAR(500) NOT NULL,
    requested_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE processed_webhook_events (
    event_id VARCHAR(160) PRIMARY KEY,
    payload_hash VARCHAR(64) NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL
);
